name: Publish Booking API

on:
    push:
        branches:
        - main
        - develop
        paths:
        - "booking-api/**"
        - "pom.xml"
        - ".github/workflows/core-api-publish.yml"

jobs:
    publish-booking-api:
        name: Publish Booking API
        uses: UptimeHub/infra/.github/workflows/maven-package-publish.yml@main
        with:
            java-version: '25'
            working-directory: 'booking-api'
            module: '.'
